import { Y1928, Y1933, Y1938, Y1939, Y1940, Y1941, Y1943, Y1945, Y1975 } from "./snapshots";
import type { CardDef, CardKind, EraDef, Length, RoleId, SolemnDef } from "./types";

export const SOLEMN: Record<string, SolemnDef> = {
  holodomor: {
    id: "holodomor",
    title: "The record: the famine of 1932–33",
    paragraphs: [
      "In 1932 and 1933 a famine struck the Soviet Union during forced collectivization. In Ukraine it is known as the Holodomor. Grain was seized, villages were blockaded, and people were stopped from leaving to find food.",
      "Anne Applebaum, in Red Famine, places the death toll in Ukraine at about 3.9 million. Kazakhstan and other Soviet regions also suffered mass death. Estimates differ. The fact of a man-made famine does not.",
      "This panel is not a card, a tile, or a score. Nothing in the game treats those deaths as a resource.",
    ],
    source: "Anne Applebaum, Red Famine (2017)",
  },
  nanjing: {
    id: "nanjing",
    title: "The record: Nanjing, winter 1937–38",
    paragraphs: [
      "Japanese troops took Nanjing, then the capital of the Republic of China, in December 1937. For weeks they massacred civilians and prisoners and committed widespread rape.",
      "The International Military Tribunal for the Far East found that more than 200,000 people were killed. Chinese estimates are higher. Historians do not share one number. They agree the massacre was vast.",
      "The war in China had begun at the Marco Polo Bridge on 7 July 1937, years before Pearl Harbor. This panel is not a move and not a score.",
    ],
    source: "Judgment of the International Military Tribunal for the Far East; Rana Mitter, China's War with Japan",
  },
  holocaust: {
    id: "holocaust",
    title: "The record: the Holocaust",
    paragraphs: [
      "The Holocaust was the systematic, state-sponsored murder of six million Jews by Nazi Germany, its allies, and collaborators. Millions of other civilians were murdered as well, including Roma people, people with disabilities, Poles, Soviet prisoners of war, and political opponents.",
      "Mass shooting expanded with the invasion of the Soviet Union in 1941. The Wannsee Conference of 20 January 1942 coordinated deportation and murder that had already begun. Nazi leaders called the plan the “Final Solution.” The words mean the planned murder of Europe’s Jews.",
      "This panel is not a move. It gives no points. Nothing on this map treats those deaths as a score.",
    ],
    source: "United States Holocaust Memorial Museum",
  },
};

function c(
  id: string,
  kind: CardKind,
  title: string,
  claim: string,
  verdict: string,
  insight: boolean,
  whatIf = false,
): CardDef {
  return { id, kind, title, claim, verdict, insight, whatIf };
}

function hands(rows: Record<RoleId, [CardDef, CardDef]>): Record<RoleId, [CardDef, CardDef]> {
  return rows;
}

export const FULL_ERAS: EraDef[] = [
  {
    id: "rise",
    startYear: 1922,
    endYear: 1928,
    ticker: "1922",
    name: "Marches and funerals",
    headline: "BLACKSHIRTS ENTER ROME",
    dateline: "28 October 1922",
    deck: "A king refuses to fight a march, and a politician becomes prime minister. A year later, a copy of that march fails in Munich.",
    pages: [
      "On 28 October 1922 Mussolini’s Blackshirts marched on Rome. King Victor Emmanuel III would not back martial law, and he asked Mussolini to form a government. The march was force and a bargain. It was not proof that no state can say no.",
      "Hitler tried to copy the success. On 8–9 November 1923 the Beer Hall Putsch in Munich failed. He was jailed and dictated Mein Kampf. Lenin died on 21 January 1924. Stalin, general secretary since 1922, outmaneuvered his rivals through the decade. The first Five-Year Plan was launched in 1928. Germany, in these years, is still the Weimar Republic.",
    ],
    source: "R. J. B. Bosworth, Mussolini; Ian Kershaw, Hitler; Oleg Khlevniuk, Stalin",
    cause: "A government split, and a king who would not use the army.",
    effect: "Mussolini took office in 1922. Hitler’s 1923 coup did not.",
    snapshot: Y1928,
    question: {
      prompt: "Why did Mussolini’s March on Rome put him in office when Hitler’s 1923 coup failed?",
      choices: [
        "The Italian king refused martial law and invited Mussolini to form a government. The Munich putsch was defeated.",
        "Both men won a majority of the national vote in the same month.",
        "The League of Nations appointed both of them.",
        "Britain declared war on Italy and Germany in 1922.",
      ],
      answer: 0,
      explain:
        "The march reached Rome on 28 October 1922, and the king chose Mussolini as prime minister. The Beer Hall Putsch of 8–9 November 1923 failed. A march is not destiny. It depends on who holds the state.",
    },
    cards: hands({
      allies: [
        c(
          "rome-bargain",
          "event",
          "A king’s decision",
          "The march worked because the king would not sign the order to stop it.",
          "Victor Emmanuel III refused martial law and asked Mussolini to form a government. The appointment, not a won battle, put him in office.",
          true,
        ),
        c(
          "rome-vote",
          "event",
          "A free majority",
          "Mussolini already had a democratic majority, so the march was a parade.",
          "He did not take office by winning a majority that week. The king’s refusal of force was the hinge.",
          false,
        ),
      ],
      soviet: [
        c(
          "stalin-post",
          "event",
          "After Lenin",
          "Stalin was already general secretary when Lenin died, and he used the post.",
          "He had held the office since 1922. Lenin died on 21 January 1924. Dominance came by outmaneuvering rivals, not by a single election day.",
          true,
        ),
        c(
          "stalin-instant",
          "event",
          "Dictator on the funeral day",
          "Stalin became an unchallenged dictator the day Lenin died.",
          "He was not unchallenged in January 1924. The defeat of Trotsky and the others took the rest of the decade.",
          false,
        ),
      ],
      axis: [
        c(
          "putsch-fail",
          "event",
          "Munich fails",
          "The Beer Hall Putsch of November 1923 collapsed. Hitler was not in power.",
          "The coup of 8–9 November 1923 failed. Jail and Mein Kampf followed. The contrast with Rome is the lesson.",
          true,
        ),
        c(
          "putsch-win",
          "event",
          "Munich succeeds",
          "The putsch made Hitler chancellor in 1923.",
          "It did not. The chancellorship is 30 January 1933, and it came by appointment.",
          false,
        ),
      ],
      analyst: [
        c(
          "treaty-raw",
          "treaty",
          "A raw peace",
          "Resentment of the 1919 settlement gave extremists an audience. It did not by itself appoint them.",
          "Versailles was a real grievance in German politics. The appointments of 1922 and 1933 still needed elites who chose to deal.",
          true,
        ),
        c(
          "treaty-only",
          "treaty",
          "The treaty explains everything",
          "The Treaty of Versailles, by itself, made dictatorship automatic.",
          "The treaty fed resentment. Italy’s king and Germany’s later president still made choices. Automatic is the wrong word.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "spain-1923",
          "event",
          "Spain’s own coup",
          "Primo de Rivera seized power in Spain in September 1923. Franco is not yet the story.",
          "Spain’s dictatorship in the 1920s was Primo de Rivera’s, under the king. Franco’s war begins in 1936.",
          true,
        ),
        c(
          "franco-1922",
          "event",
          "Franco already rules",
          "Franco has been dictator of Spain since the March on Rome.",
          "He has not. The civil war starts in 1936, and he rules from the Nationalist victory in 1939 until 1975.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Five-Year Plan", text: "The first Five-Year Plan, launched in 1928, turned the Soviet state toward forced industrial targets." },
      { title: "Mein Kampf", text: "Hitler dictated Mein Kampf in prison after the failed putsch. The book was a program, not a victory." },
    ],
    portrait: "mussolini",
  },
  {
    id: "crisis",
    startYear: 1929,
    endYear: 1933,
    ticker: "1933",
    name: "Panic and the chancellorship",
    headline: "A CHANCELLOR IS SWORN IN",
    dateline: "30 January 1933",
    deck: "The Nazis are the largest party, not a majority. The president hands Hitler the office anyway.",
    pages: [
      "The Depression after 1929 wiped out savings and work. In Germany the Nazi vote rose and still missed a majority. On 30 January 1933 President Hindenburg appointed Hitler chancellor, with conservative partners who thought they could use him.",
      "The Reichstag fire of 27 February was followed the next day by a decree that suspended civil liberties. The Enabling Act of 23 March let the cabinet make laws without the Reichstag, including laws that broke the constitution. The Social Democrats voted no. Communist deputies were excluded. In Asia, the Kwantung Army seized Manchuria after the Mukden Incident of 18 September 1931. Tojo did not order that incident. He was a Kwantung officer who later became the army’s chief of staff, in 1937.",
    ],
    source: "Richard J. Evans, The Coming of the Third Reich; Rana Mitter, China's War with Japan",
    cause: "Mass unemployment, a plural election, and elites who chose a coalition.",
    effect: "Hitler entered office by appointment, then used decree and the Enabling Act to end parliamentary government.",
    snapshot: Y1933,
    solemnId: "holodomor",
    question: {
      prompt: "Which description of 30 January 1933 matches the record?",
      choices: [
        "Hindenburg appointed Hitler chancellor. The Nazis did not have a majority.",
        "Hitler won more than half the vote and became dictator that hour.",
        "The Beer Hall Putsch succeeded on this date.",
        "The Enabling Act was passed in 1928.",
      ],
      answer: 0,
      explain:
        "The November 1932 election left the Nazis short of a majority. Hindenburg appointed Hitler on 30 January 1933. The Enabling Act was 23 March 1933. The 1923 putsch had failed.",
    },
    cards: hands({
      allies: [
        c(
          "depression-door",
          "event",
          "The Depression opens a door",
          "Economic collapse raised the Nazi vote. It still took a president’s appointment to make Hitler chancellor.",
          "Both halves are required. The Depression was the condition. Hindenburg’s choice was the act.",
          true,
        ),
        c(
          "depression-auto",
          "event",
          "Collapse means dictatorship",
          "Any country in a depression must become a dictatorship.",
          "The United States and Britain were in the same Depression and did not hand power to a fascist party. Conditions are not a script.",
          false,
        ),
      ],
      soviet: [
        c(
          "collectivize",
          "event",
          "The plan’s cost",
          "Collectivization and the first Five-Year Plan were state policy, and the famine was a consequence of policy.",
          "The famine of 1932–33 was man-made. Read the record panel. It is not a production bonus.",
          true,
        ),
        c(
          "harvest-weather",
          "event",
          "Only the weather",
          "The deaths of 1932–33 were only a natural harvest failure.",
          "Bad harvests happened. Seizure of grain, blockades, and the ban on leaving made the famine a political act. Applebaum’s Red Famine is the account used here.",
          false,
        ),
      ],
      axis: [
        c(
          "no-majority",
          "event",
          "Largest party, not a majority",
          "Hitler reached the chancellorship without a majority vote.",
          "That is the record. The dictatorship was constructed after the appointment, by the fire decree and the Enabling Act.",
          true,
        ),
        c(
          "majority-myth",
          "propaganda",
          "The people elected a dictator",
          "A majority of Germans voted to make Hitler dictator in January 1933.",
          "They did not. Propaganda later made the appointment look like destiny. The votes do not say that.",
          false,
        ),
      ],
      analyst: [
        c(
          "slogan-law",
          "propaganda",
          "From slogan to statute",
          "Posters and radio mattered, and the Enabling Act mattered more, because it changed what was legal.",
          "Propaganda prepared consent. The act of 23 March 1933 let the cabinet govern without the Reichstag. Watch the law, not only the picture.",
          true,
        ),
        c(
          "posters-enough",
          "propaganda",
          "Posters were the whole state",
          "Once the posters were up, no law had to change.",
          "The decree after the Reichstag fire, and the Enabling Act, changed the law. A picture is not a constitution.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "mukden",
          "event",
          "Manchuria, 1931",
          "The Kwantung Army seized Manchuria in 1931. Tojo’s premiership is still ten years away.",
          "The Mukden Incident was 18 September 1931. Manchukuo was set up in 1932. Tojo became prime minister on 18 October 1941.",
          true,
        ),
        c(
          "tojo-1931",
          "event",
          "Tojo orders Mukden",
          "Tojo personally ordered the 1931 seizure, as prime minister.",
          "He was not prime minister in 1931, and he did not give that order. He rose through the Kwantung Army and became its chief of staff in 1937.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Reichstag fire", text: "The Reichstag burned on 27 February 1933. The decree of 28 February suspended basic rights." },
      { title: "Manchukuo", text: "Japan proclaimed the puppet state of Manchukuo in 1932, with Puyi as its figurehead." },
    ],
    portrait: "hitler",
  },
  {
    id: "expansion",
    startYear: 1934,
    endYear: 1938,
    ticker: "1938",
    name: "Defiance and appeasement",
    headline: "MUNICH: A BARGAIN WITHOUT CZECHOSLOVAKIA",
    dateline: "30 September 1938",
    deck: "The Sudetenland is handed over. Chamberlain speaks of peace for our time. Prague has not yet fallen. It will.",
    pages: [
      "Hitler consolidated the dictatorship in 1934, including the murders at the end of June known as the Night of the Long Knives, and the Führer title after Hindenburg died on 2 August. The Nuremberg Laws of 15 September 1935 stripped German Jews of citizenship. On 7 March 1936 troops entered the Rhineland. France and Britain did not fight.",
      "Italy invaded Ethiopia on 3 October 1935 and took Addis Ababa on 5 May 1936. The Spanish Civil War began in July 1936. Germany and Italy armed Franco. Guernica was bombed on 26 April 1937. Japan’s full war in China dates from the Marco Polo Bridge, 7 July 1937. Austria was annexed on 12 March 1938. Munich, 29–30 September 1938, ceded the Sudetenland. Kristallnacht, 9–10 November 1938, was a state-backed pogrom. The Great Purge in the Soviet Union, from 1936 to 1938, ran at the same time: archival totals record about 680,000 executions in 1937 and 1938.",
    ],
    source: "Evans, The Third Reich in Power; Paul Preston, Franco; Khlevniuk, Stalin",
    cause: "Democracies protested the Rhineland and then bargained at Munich.",
    effect: "Hitler took Austria and the Sudetenland without a war, and judged that the next grab would also go unfought.",
    snapshot: Y1938,
    solemnId: "nanjing",
    badge: "warning-signs",
    question: {
      prompt: "What did the Munich Agreement actually do?",
      choices: [
        "It gave the Sudetenland to Germany. Czechoslovakia did not write the terms.",
        "It sent British troops into Berlin.",
        "It was the alliance of Germany and the Soviet Union.",
        "It ended the Spanish Civil War.",
      ],
      answer: 0,
      explain:
        "Chamberlain, Daladier, Hitler, and Mussolini agreed on 29–30 September 1938. Czech leaders were not a party to the talks. On 15 March 1939 Germany occupied the rest of Bohemia and Moravia.",
    },
    cards: hands({
      allies: [
        c(
          "rhineland-stand",
          "response",
          "Name the missed test",
          "March 1936 was a test. Britain and France protested and did not use force.",
          "Troops entered the Rhineland on 7 March 1936 under orders to pull back if France fought. The democracies did not fight. That what-if is a gamble in the record, not a fantasy of an easy war.",
          true,
          true,
        ),
        c(
          "peace-for-our-time",
          "response",
          "Call Munich the end",
          "Chamberlain’s phrase means Hitler has no further territorial aims.",
          "He said “peace for our time” on 30 September 1938. March 1939 broke the promise. Churchill was a critic in Parliament, not yet prime minister.",
          false,
        ),
      ],
      soviet: [
        c(
          "purge-toll",
          "event",
          "The Great Terror",
          "The purge of 1936–38 executed hundreds of thousands and filled the camps. It was not a strength bonus.",
          "Archival figures show about 680,000 executions in 1937 and 1938. The show trials destroyed the old Bolshevik leadership and much of the officer corps.",
          true,
        ),
        c(
          "purge-order",
          "event",
          "Only a tidy reform",
          "The trials were a routine anti-corruption drive with little loss of life.",
          "The show trials and the NKVD operations were a terror. Khlevniuk’s account, using the archives, is the one this class uses.",
          false,
        ),
      ],
      axis: [
        c(
          "order-of-grabs",
          "event",
          "Put the grabs in order",
          "Rhineland, then Austria, then the Sudetenland. Prague is not yet occupied in September 1938.",
          "7 March 1936, 12 March 1938, 30 September 1938. The occupation of Prague is 15 March 1939. Order is the whole point of this desk.",
          true,
        ),
        c(
          "one-gulp",
          "event",
          "All in one year",
          "The Rhineland, Austria, and Poland were taken in 1936.",
          "Poland is 1939. Mixing the dates hides how appeasement looked reasonable to some people for a time, and then failed.",
          false,
        ),
      ],
      analyst: [
        c(
          "who-was-absent",
          "treaty",
          "Who was not in the room",
          "Munich decided a Czech border without Czechoslovakia.",
          "That absence is the fact to remember. A bargain about a country, made over its head, is not a peace that country agreed to.",
          true,
        ),
        c(
          "four-happy",
          "propaganda",
          "Four signatures, no victim",
          "If four leaders sign, the country they discussed has consented.",
          "Consent requires the people whose land it is. Czechoslovakia was not one of the signers.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "two-wars",
          "event",
          "Spain and China",
          "Guernica was 26 April 1937. The China war widened on 7 July 1937. These are not the same front.",
          "Franco’s Nationalists received German and Italian aid. Japan was fighting the Republic of China. Nanjing’s massacre is on the record panel.",
          true,
        ),
        c(
          "one-war",
          "event",
          "One world war already",
          "The Spanish Civil War and Pearl Harbor are the same campaign in 1937.",
          "Pearl Harbor is December 1941. The civil war ends in April 1939, before the European war begins.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Ethiopia", text: "The League of Nations condemned Italy’s invasion of Ethiopia and did not stop it." },
      { title: "Nuremberg Laws", text: "On 15 September 1935 the Nuremberg Laws defined citizenship by ancestry and banned marriage between Jews and non-Jews." },
    ],
    portrait: "chamberlain",
  },
  {
    id: "war",
    startYear: 1939,
    endYear: 1940,
    ticker: "1940",
    name: "The war opens",
    headline: "FRANCE SIGNS AN ARMISTICE",
    dateline: "22 June 1940",
    deck: "Poland has already fallen. Paris is occupied. Britain has a new prime minister, and the island holds.",
    pages: [
      "Germany occupied Prague on 15 March 1939. Italy invaded Albania on 7 April and signed the Pact of Steel with Germany on 22 May. The Nazi-Soviet Pact of 23 August carried a secret protocol on Eastern Europe. Germany invaded Poland on 1 September. Britain and France declared war on 3 September. The Soviet Union invaded eastern Poland on 17 September. The Winter War against Finland ran from 30 November 1939 to 13 March 1940.",
      "On 9 April 1940 Germany invaded Denmark and Norway. Sweden stayed neutral. On 10 May Churchill became prime minister as Germany invaded the Low Countries and France. Paris was occupied on 14 June. The armistice of 22 June left Philippe Pétain at the head of Vichy France. Charles de Gaulle, from London, rejected that ending on 18 June. The Battle of Britain stopped an invasion. Japan joined Germany and Italy in the Tripartite Pact on 27 September 1940. Franco, victorious in Spain since 1 April 1939, met Hitler at Hendaye in October and kept Spain out of the war.",
    ],
    source: "Richard J. Evans, The Third Reich at War; Paul Preston, Franco",
    cause: "A pact that freed Hitler’s eastern border, then a gamble on a short war in the west.",
    effect: "Poland was destroyed as an independent state, France was defeated, and Britain stayed in the war.",
    snapshot: Y1940,
    badge: "named-pact",
    battle: {
      id: "britain",
      title: "The Battle of Britain",
      date: "Summer and autumn 1940",
      attacker: "German air force",
      defender: "Britain",
      historical: "defender",
      summary: "Germany needed command of the air to invade. It did not get it. The island was not occupied.",
      fromId: "germany",
      toId: "britain",
    },
    question: {
      prompt: "The Nazi-Soviet Pact of August 1939 is best described as…",
      choices: [
        "A public non-aggression pact plus a secret division of Eastern Europe.",
        "A promise that Germany would become communist.",
        "The same document as the Munich Agreement.",
        "An alliance that included the United States.",
      ],
      answer: 0,
      explain:
        "Molotov and Ribbentrop signed on 23 August 1939. The secret protocol divided spheres. The Soviet Union invaded eastern Poland on 17 September, sixteen days after Germany’s attack.",
    },
    cards: hands({
      allies: [
        c(
          "churchill-date",
          "response",
          "10 May 1940",
          "Churchill becomes prime minister the day the western invasion begins, not at Munich.",
          "Munich was Chamberlain’s policy, in 1938. Churchill entered office on 10 May 1940. Dates stop the myth that he “lost” Munich.",
          true,
        ),
        c(
          "churchill-munich",
          "response",
          "Churchill signed Munich",
          "Churchill was prime minister and signed the Munich Agreement.",
          "He was not prime minister, and he did not sign it. Chamberlain did. Churchill criticized the bargain from outside the government.",
          false,
        ),
      ],
      soviet: [
        c(
          "pact-record",
          "alliance",
          "Name the secret protocol",
          "The pact with Germany divided Eastern Europe on paper, then the Red Army entered eastern Poland.",
          "The protocol was secret. The invasion of 17 September 1939 was public. The Winter War with Finland followed on 30 November.",
          true,
        ),
        c(
          "pact-peace",
          "alliance",
          "A pact for peace in general",
          "The pact was only a sincere promise with no territorial clauses.",
          "The secret clauses were about territory. Calling it a simple peace hides the division of Poland.",
          false,
        ),
      ],
      axis: [
        c(
          "two-1940s",
          "event",
          "April, then May",
          "Denmark and Norway were invaded on 9 April 1940. France and the Low Countries followed on 10 May.",
          "Sweden was not invaded. The armistice with France was 22 June. Pétain led Vichy. De Gaulle did not accept it.",
          true,
        ),
        c(
          "sweden-too",
          "event",
          "All of Scandinavia",
          "Sweden was conquered on the same morning as Denmark.",
          "Sweden stayed neutral. Painting it as occupied teaches the wrong map.",
          false,
        ),
      ],
      analyst: [
        c(
          "vichy-word",
          "propaganda",
          "What Vichy called itself",
          "Vichy said it was saving France. It collaborated with the occupation.",
          "Pétain’s government asked for the armistice and worked with German power. De Gaulle’s 18 June appeal is the counter-fact: not every French voice accepted it.",
          true,
        ),
        c(
          "vichy-free",
          "propaganda",
          "Vichy was Free France",
          "Pétain and de Gaulle led the same government in 1940.",
          "They led opposite choices. Pétain headed Vichy. De Gaulle called for resistance from exile.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "hendaye",
          "alliance",
          "Franco stays out",
          "Franco had won by April 1939, met Hitler in 1940, and did not declare war.",
          "The Hendaye meeting was 23 October 1940. Spain sent a volunteer Blue Division to the Eastern Front later and still avoided a formal entry into the war.",
          true,
        ),
        c(
          "franco-axis-war",
          "alliance",
          "Spain declares war in 1939",
          "Franco brought Spain into the war beside Germany in September 1939.",
          "He did not. Neutrality, later called non-belligerence, was his policy. The civil war was over. The world war was not his declaration.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Albania", text: "Italy invaded Albania on 7 April 1939, before the German attack on Poland." },
      { title: "Winter War", text: "The Soviet Union attacked Finland on 30 November 1939. The peace of 13 March 1940 took Finnish land and did not conquer Finland." },
    ],
    portrait: "churchill",
  },
  {
    id: "global",
    startYear: 1941,
    endYear: 1941,
    ticker: "1941",
    name: "The world at war",
    headline: "TWO OCEANS, ONE YEAR",
    dateline: "1941",
    deck: "June: Germany invades the Soviet Union. December: Japan attacks Pearl Harbor. The United States is in.",
    pages: [
      "On 6 April 1941 Germany invaded Yugoslavia and Greece. Italy’s own attack on Greece, begun on 28 October 1940, had stalled. Operation Barbarossa opened on 22 June 1941. Axis armies took huge stretches of Soviet land and did not take the state. The siege of Leningrad and the drive toward Moscow were the same war. So were the shooting squads that followed the front.",
      "Hideki Tojo became prime minister on 18 October 1941. Japan attacked Pearl Harbor on 7 December, which was 8 December in Japan. The United States abandoned isolation in practice and declared war. By the middle of 1942 Japan held the Philippines, Singapore, Malaya, and the Dutch East Indies. Hirohito approved the decision for war as emperor. He was not tried after the defeat. Herbert Bix argues he was an active monarch, not a blank signature. He was also not a lone plotter writing naval orders himself.",
    ],
    source: "Evans, The Third Reich at War; Herbert P. Bix, Hirohito and the Making of Modern Japan",
    cause: "Hitler broke his own pact and opened a second land war. Japan struck the United States to break the embargo and the fleet.",
    effect: "The Soviet Union and the United States were both at war with the Axis. Neither front was a short campaign.",
    snapshot: Y1941,
    battle: {
      id: "barbarossa",
      title: "The invasion of the Soviet Union",
      date: "22 June 1941",
      attacker: "Germany and its partners",
      defender: "Soviet Union",
      historical: "attacker",
      summary: "The invasion drove hundreds of miles into Soviet land. It did not force a Soviet surrender. The shade means a front, not a finished conquest.",
      fromId: "germany",
      toId: "wsoviet",
    },
    question: {
      prompt: "Which pairing of 1941 dates is correct?",
      choices: [
        "Barbarossa on 22 June, and Pearl Harbor on 7 December.",
        "Pearl Harbor in June, and Barbarossa in 1938.",
        "Both attacks in 1936.",
        "D-Day and the Anschluss.",
      ],
      answer: 0,
      explain:
        "The Soviet invasion began on 22 June 1941. Pearl Harbor was 7 December 1941. Tojo had been prime minister since 18 October. Lend-Lease, the American supply law, had passed on 11 March 1941, before either attack.",
    },
    cards: hands({
      allies: [
        c(
          "lend-lease",
          "alliance",
          "Aid before the declaration",
          "The United States was aiding Britain before Pearl Harbor, and the attack ended the argument for staying out.",
          "Lend-Lease became law on 11 March 1941. The Atlantic Charter was issued in August. Pearl Harbor on 7 December brought a declaration of war, which aid alone had not.",
          true,
        ),
        c(
          "asleep-forever",
          "response",
          "Still neutral in 1942",
          "Pearl Harbor did not change American policy.",
          "It did. Congress declared war on Japan on 8 December 1941. Germany declared war on the United States on 11 December.",
          false,
        ),
      ],
      soviet: [
        c(
          "not-conquered",
          "event",
          "Invaded, not replaced",
          "Barbarossa was a catastrophe and not a Soviet surrender.",
          "The state held, at a cost later counted at about 27 million Soviet military and civilian deaths in the whole war. The 1941 map is a front.",
          true,
        ),
        c(
          "moscow-fell",
          "event",
          "Moscow fell in June",
          "The capital surrendered in the first week of Barbarossa.",
          "It did not. German troops were stopped short of Moscow in December 1941. The war went on.",
          false,
        ),
      ],
      axis: [
        c(
          "tojo-date",
          "event",
          "Prime minister in October",
          "Tojo took office in October 1941, after a decade of war and seizure in Asia, not in 1931.",
          "18 October 1941. The China war was already four years old. Pearl Harbor was his government’s gamble, planned by the navy, approved by the cabinet and the emperor.",
          true,
        ),
        c(
          "tojo-emperor",
          "event",
          "Tojo was emperor",
          "Tojo and Hirohito were the same office.",
          "Hirohito was the emperor. Tojo was an army officer and then prime minister. Mixing them erases the trial record and the throne.",
          false,
        ),
      ],
      analyst: [
        c(
          "two-dates",
          "event",
          "Do not merge the dates",
          "June and December 1941 are different attacks, on different countries.",
          "One is the Soviet Union. One is the United States fleet at Hawaii, with attacks on other empires the same week. A student who merges them cannot explain the war.",
          true,
        ),
        c(
          "one-morning",
          "propaganda",
          "One surprise morning",
          "Barbarossa and Pearl Harbor happened on the same morning.",
          "They were five months apart. Propaganda likes one dramatic dawn. The calendar does not.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "china-already",
          "event",
          "China was already at war",
          "Pearl Harbor did not start Japan’s war. China had been fighting since 1937.",
          "Marco Polo Bridge was 7 July 1937. By December 1941 that war was old. Chiang Kai-shek’s government was in Chongqing. The Communist armies under Mao were a wary partner in a united front.",
          true,
        ),
        c(
          "china-later",
          "event",
          "China’s war starts in 1941",
          "Japan and China were at peace until Pearl Harbor.",
          "They were not. Nanjing was 1937. Treating 1941 as the start erases the Chinese dead of the years before.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Lend-Lease", text: "Roosevelt signed Lend-Lease on 11 March 1941, supplying Allied countries before the United States was a formal belligerent." },
      { title: "United front", text: "Chiang and the Communists had a brittle united front against Japan. It did not survive the peace." },
    ],
    portrait: "tojo",
  },
  {
    id: "turning",
    startYear: 1942,
    endYear: 1943,
    ticker: "1943",
    name: "Turning points",
    headline: "THE SIXTH ARMY SURRENDERS",
    dateline: "2 February 1943",
    deck: "Stalingrad does not empty the map. It tells you the advance has been broken.",
    pages: [
      "Midway, 4–7 June 1942, cost Japan four carriers and ended the plan to keep expanding across the Pacific. In North Africa, El Alamein in the autumn of 1942 and the Torch landings of 8 November 1942 put the Axis on the defensive. Tunis fell in May 1943.",
      "The German Sixth Army surrendered at Stalingrad on 2 February 1943. On 25 July the king dismissed Mussolini. The armistice was announced on 8 September, and Germany occupied the north of Italy. Partisans killed Mussolini on 28 April 1945. The killing of Europe’s Jews was already policy: shooting units from 1941, and the Wannsee Conference on 20 January 1942. The record panel carries that fact. This battle does not.",
    ],
    source: "Evans, The Third Reich at War; United States Holocaust Memorial Museum; Bosworth, Mussolini",
    cause: "Overextended armies met opponents who could replace losses. Allies coordinated. The Axis could not.",
    effect: "The Soviet Union held the east, the Axis lost Africa, and Mussolini fell. Nazi occupation in the west continued.",
    snapshot: Y1943,
    solemnId: "holocaust",
    badge: "turning",
    battle: {
      id: "stalingrad",
      title: "Stalingrad",
      date: "August 1942 – 2 February 1943",
      attacker: "German Sixth Army",
      defender: "Soviet armies",
      historical: "defender",
      summary: "The city fight ended with a German surrender. It was a turning point, not the end of the occupation of Europe.",
      fromId: "germany",
      toId: "wsoviet",
    },
    question: {
      prompt: "Why is Stalingrad called a turning point if France was still occupied?",
      choices: [
        "It broke the German advance in the east. It did not free Western Europe on the same day.",
        "It ended the war in February 1943.",
        "It was the invasion of Italy by the Soviet navy.",
        "It restored the Weimar Republic.",
      ],
      answer: 0,
      explain:
        "The Sixth Army surrendered on 2 February 1943. Paris was still under occupation. D-Day was 6 June 1944. A turning point changes direction. It is not the last day.",
    },
    cards: hands({
      allies: [
        c(
          "two-fronts-turn",
          "event",
          "East and Pacific",
          "Stalingrad and Midway are both in this turn of the war, and they are not the same battle.",
          "Midway was June 1942. Stalingrad’s surrender was February 1943. North Africa closed in May 1943. Name them separately.",
          true,
        ),
        c(
          "one-battle",
          "event",
          "One battle did it all",
          "Stalingrad also liberated Paris and defeated the Japanese navy.",
          "It did not. Paris was 1944. Midway was a different ocean. Keep the fronts apart.",
          false,
        ),
      ],
      soviet: [
        c(
          "cost-stated",
          "event",
          "Say the cost",
          "The Soviet victory at Stalingrad was real, and the country’s war dead were about 27 million.",
          "The figure comes from late Soviet and Russian archival accounting, often given as about 26.6 million and taught as about 27 million. A victory that large was also a wound.",
          true,
        ),
        c(
          "cheap-win",
          "event",
          "A cheap encirclement",
          "Stalingrad was a small skirmish with little loss of life.",
          "It was among the largest battles ever fought. Treating it as cheap insults the record and the people in the city.",
          false,
        ),
      ],
      axis: [
        c(
          "mussolini-clock",
          "event",
          "July 1943",
          "The king dismissed Mussolini on 25 July 1943. The 1922 march had a matching end: the king could still act.",
          "The same monarchy that had invited him in could remove him. Germany then kept a puppet regime in the north until April 1945.",
          true,
        ),
        c(
          "mussolini-1940",
          "event",
          "He fell in 1940",
          "Mussolini lost office when France fell.",
          "He entered the war in June 1940, beside Germany. He fell in July 1943, after Africa and as Sicily was invaded.",
          false,
        ),
      ],
      analyst: [
        c(
          "not-a-score",
          "response",
          "The record is not the battle",
          "The Holocaust panel is not a campaign result and adds nothing to Insight.",
          "Six million Jews, and millions of other civilians, are the museum’s accounting. Wannsee coordinated a murder already underway. If a teammate treats it as points, stop the game and reread the panel.",
          true,
        ),
        c(
          "add-the-points",
          "response",
          "Add it to the meter",
          "The killing should raise the control meter, like a province.",
          "No. The meter, where it appears, is about armies and governments. The murder of civilians is not a province and not a point.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "still-china",
          "event",
          "China keeps fighting",
          "The turning points in Europe and at Midway do not end the war in China.",
          "Chiang’s government and the Communist forces were still in the field. Japan does not surrender until 1945.",
          true,
        ),
        c(
          "china-over",
          "event",
          "China’s war ended at Midway",
          "After June 1942 Japan withdrew from China.",
          "It did not. The China front lasted until the surrender in 1945.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Midway", text: "The Battle of Midway, 4–7 June 1942, sank four Japanese carriers and is the usual marker for the Pacific turn." },
      { title: "Torch", text: "American and British troops landed in French North Africa on 8 November 1942." },
    ],
    portrait: "stalin",
  },
  {
    id: "collapse",
    startYear: 1944,
    endYear: 1945,
    ticker: "1945",
    name: "Collapse",
    headline: "THE REICH FALLS",
    dateline: "30 April 1945",
    deck: "Hitler is dead in Berlin. The shade of Nazi rule comes off the map. The counting of the dead does not stop.",
    pages: [
      "Allied armies landed in Normandy on 6 June 1944. Tojo resigned on 18 July, after Saipan fell. Paris was liberated in August. Roosevelt died on 12 April 1945, before victory, and Truman became president. Hitler died by suicide on 30 April. Mussolini was killed by partisans on 28 April. Germany surrendered. In the West, 8 May 1945 is VE Day.",
      "Yalta, 4–11 February 1945, put Roosevelt, Churchill, and Stalin around one table while the Soviet army was already in Eastern Europe. Promises of free elections in Poland were not kept. Potsdam, 17 July to 2 August, was Truman, Stalin, and Churchill, then Attlee. The United States bombed Hiroshima on 6 August and Nagasaki on 9 August. Japan announced surrender on 15 August. The formal surrender was on 2 September 1945, aboard the USS Missouri.",
    ],
    source: "Office of the Historian, U.S. Department of State; Ian Kershaw, Hitler",
    cause: "Allied armies closed from west and east, and Japan’s defensive perimeter broke.",
    effect: "Nazi Germany was destroyed, Japan surrendered, and the survivors inherited occupation zones and a coming Cold War.",
    snapshot: Y1945,
    question: {
      prompt: "Which statement about the spring of 1945 is accurate?",
      choices: [
        "Roosevelt died on 12 April. Hitler died on 30 April. Germany then surrendered.",
        "Hitler died in 1944, on D-Day.",
        "Roosevelt attended the surrender ceremony in Tokyo.",
        "Tojo became prime minister in May 1945.",
      ],
      answer: 0,
      explain:
        "FDR died on 12 April 1945 and did not see VE Day. Hitler died on 30 April. Japan’s formal surrender was 2 September, which Truman presided over as president. Tojo had resigned in July 1944.",
    },
    cards: hands({
      allies: [
        c(
          "conferences",
          "treaty",
          "Three conferences",
          "Tehran, Yalta, and Potsdam are different meetings, with a changing cast.",
          "Tehran was November–December 1943. Yalta was February 1945, with Roosevelt. Potsdam was July–August 1945, with Truman. Stalin attended all three.",
          true,
        ),
        c(
          "one-meeting",
          "treaty",
          "One meeting called Yalta",
          "Tehran, Yalta, and Potsdam were a single afternoon.",
          "They were years apart in the case of Tehran, and the American president changed between Yalta and Potsdam because Roosevelt died.",
          false,
        ),
      ],
      soviet: [
        c(
          "on-the-ground",
          "alliance",
          "The army was already there",
          "Yalta did not conjure Soviet power in Eastern Europe. The Red Army was already present.",
          "The agreements talked of free elections. Poland’s were not free. Presence of the army explains more than a signature does, and it does not excuse the sphere that followed.",
          true,
        ),
        c(
          "paper-only",
          "alliance",
          "A signature created the bloc",
          "Eastern Europe became communist because of a clause, with no army involved.",
          "The clause mattered, and the army mattered more. People in Warsaw and Prague were not consulted in any free way.",
          false,
        ),
      ],
      axis: [
        c(
          "end-dates",
          "event",
          "April, then May, then August",
          "Mussolini died on 28 April 1945, Hitler on 30 April, Germany surrendered in May, and Japan in August and September.",
          "Keep the two surrenders apart. VE Day is not VJ Day. Tojo lived to be tried. He was executed on 23 December 1948.",
          true,
        ),
        c(
          "same-day",
          "event",
          "Everyone on one day",
          "Germany and Japan surrendered on 30 April 1945.",
          "Japan’s announcement was 15 August, and the signing was 2 September. Hiroshima was 6 August. Nagasaki was 9 August.",
          false,
        ),
      ],
      analyst: [
        c(
          "zones",
          "response",
          "Read the new shade",
          "When Nazi red leaves Germany, the replacement is occupation, not a return to 1922.",
          "Four powers occupied Germany. Austria was occupied and later neutralized. Liberation and occupation are both real words in 1945.",
          true,
        ),
        c(
          "reset",
          "response",
          "The map resets to 1922",
          "May 1945 puts every border back where it was in 1922.",
          "It does not. Poland’s border moved. Germany was divided. Korea was divided. The shade has changed meaning.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "japan-out",
          "event",
          "Japan leaves China",
          "Surrender in 1945 ends the Japanese occupation. It opens the Chinese civil war again.",
          "Chiang and Mao were no longer united by a common enemy. The civil war ran until 1949. Franco, meanwhile, was untouched by this surrender and still in office.",
          true,
        ),
        c(
          "mao-1945",
          "event",
          "Mao already rules in 1945",
          "The People’s Republic was proclaimed on the day Japan surrendered.",
          "The proclamation was 1 October 1949. In 1945 the civil war is resuming, not finished.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "D-Day", text: "Normandy was 6 June 1944. It opened a Western front in France. It was not the day the war ended." },
      { title: "Hiroshima", text: "The uranium bomb on Hiroshima was 6 August 1945. The plutonium bomb on Nagasaki was 9 August. Japan’s emperor then announced surrender." },
    ],
    portrait: "fdr",
  },
  {
    id: "legacy",
    startYear: 1946,
    endYear: 1975,
    ticker: "1975",
    name: "Long shadows",
    headline: "FRANCO’S RULE ENDS",
    dateline: "20 November 1975",
    deck: "The war has been over for thirty years. One of the dictators on this map is only now dying.",
    pages: [
      "The major trial at Nuremberg ran from 20 November 1945 to 1 October 1946. The Tokyo trials ran from 1946 to 1948. Tojo was hanged on 23 December 1948. Hirohito stayed on the throne and died in 1989, beyond this timeline. Stalin imposed a sphere in Eastern Europe. Tito’s Yugoslavia broke with him. Greece did not become a Soviet satellite. Stalin died on 5 March 1953.",
      "Mao Zedong proclaimed the People’s Republic of China on 1 October 1949. Chiang Kai-shek’s government went to Taiwan. Mao was still in power in 1975 and died in 1976. Franco ruled Spain until 20 November 1975. The chronicle stops on that date because a classroom that ends in 1945 misses a dictator who outlived Hitler by three decades.",
    ],
    source: "Paul Preston, Franco; Rana Mitter, China's War with Japan; Khlevniuk, Stalin",
    cause: "Victory removed some dictators and left others. The Cold War then froze a divided map.",
    effect: "Trials recorded Nazi and Japanese wartime crimes. Franco lasted until 1975. Mao’s state lasted past him. The Soviet state outlived Stalin.",
    snapshot: Y1975,
    question: {
      prompt: "Why does this chronicle run to 1975?",
      choices: [
        "Franco ruled until his death on 20 November 1975, long after the Axis surrendered.",
        "Hitler was still alive in 1975.",
        "The Munich Agreement was signed in 1975.",
        "The Battle of Britain was fought in 1975.",
      ],
      answer: 0,
      explain:
        "Franco died on 20 November 1975. Hitler died in 1945. Mao still ruled China in 1975 and died in 1976. Ending the unit at VE Day hides how long dictatorship lasted in places the Axis never conquered, and in the states the war left behind.",
    },
    cards: hands({
      allies: [
        c(
          "trials",
          "response",
          "A court, not a footnote",
          "Nuremberg and Tokyo put leaders in a dock and made a public record of crimes.",
          "Nuremberg’s major trial opened in November 1945. The Tokyo judgment came in 1948. Courts do not undo deaths. They stop the crimes from being told only by the perpetrators.",
          true,
        ),
        c(
          "no-trial",
          "response",
          "No one was tried",
          "The Allies skipped trials and went straight home.",
          "They did not. The trials were imperfect, and they happened. Hirohito’s exemption was a political choice, which Bix and others have criticized.",
          false,
        ),
      ],
      soviet: [
        c(
          "1953",
          "event",
          "Stalin’s death",
          "Stalin died on 5 March 1953. The system he built did not die that day.",
          "The camps, the sphere, and the party continued. Khrushchev later denounced parts of the terror. That speech is not a pardon for the famine or the purge.",
          true,
        ),
        c(
          "system-ends",
          "event",
          "The state ends with him",
          "The Soviet Union dissolved in March 1953.",
          "It did not. The dissolution comes in 1991, outside this game. 1953 is a death, not a collapse of the state.",
          false,
        ),
      ],
      axis: [
        c(
          "who-outlived",
          "event",
          "Who outlived the war",
          "Hitler, Mussolini, and Tojo were dead by 1948. Franco was not.",
          "Mussolini died in April 1945, Hitler in April 1945, Tojo by execution in December 1948. Franco died in 1975. The Axis desk includes the one who stayed out and stayed in power.",
          true,
        ),
        c(
          "all-gone-1945",
          "event",
          "All five gone in 1945",
          "Franco, Stalin, and Mao also died in April 1945.",
          "None of those three died in 1945. Stalin died in 1953. Mao died in 1976. Franco died in 1975.",
          false,
        ),
      ],
      analyst: [
        c(
          "word-dictator",
          "response",
          "Use the word carefully",
          "Dictator here means a ruler who destroyed the chance to remove him. The list is not a fan club.",
          "Mussolini, Hitler, Stalin, Franco, and the wartime government of Japan fit the unit because they concentrated power and used terror. The word is a description, not a compliment.",
          true,
        ),
        c(
          "strong-man",
          "propaganda",
          "Strong leaders saved their countries",
          "The right lesson is that firm rulers were the heroes of the era.",
          "That is the propaganda. The record is appointments, terror, war, and mass death. Insight points come from rejecting that slogan.",
          false,
        ),
      ],
      chinaSpain: [
        c(
          "1949-1975",
          "event",
          "Mao and Franco, dated",
          "The People’s Republic begins on 1 October 1949. Franco dies on 20 November 1975.",
          "Chiang’s government survived on Taiwan. Mao’s later campaigns, including the Great Leap and the Cultural Revolution, sit beyond this game’s turns and inside the same life. One sentence is enough: they were catastrophes, and they are not buttons here.",
          true,
        ),
        c(
          "chiang-wins",
          "event",
          "Chiang rules the mainland in 1975",
          "The Nationalists won the civil war and still governed Beijing in 1975.",
          "They lost the mainland. The proclamation of the People’s Republic was 1 October 1949. Chiang died in 1975, on Taiwan, the same year Franco died.",
          false,
        ),
      ],
    }),
    asides: [
      { title: "Taiwan", text: "Chiang Kai-shek’s government retreated to Taiwan in 1949. He died on 5 April 1975." },
      { title: "Nuremberg", text: "The court sat in public. The charges included crimes against humanity, a phrase this unit should be able to explain." },
    ],
    portrait: "franco",
  },
];

export const QUICK_ERAS: EraDef[] = [
  {
    id: "quick-rise",
    startYear: 1922,
    endYear: 1933,
    ticker: "1933",
    name: "From Rome to the chancellorship",
    headline: "FROM A MARCH TO AN OATH",
    dateline: "1922–1933",
    deck: "Mussolini gets a king’s permission. Hitler’s coup fails. A decade later, a president appoints him anyway.",
    pages: [
      "28 October 1922: the March on Rome, and Mussolini becomes prime minister because the king will not use the army. 8–9 November 1923: the Beer Hall Putsch fails. Lenin dies on 21 January 1924. Stalin, general secretary since 1922, is dominant by the first Five-Year Plan in 1928.",
      "The Depression lifts the Nazi vote and does not give them a majority. Hindenburg appoints Hitler on 30 January 1933. The Enabling Act passes on 23 March. In 1931 the Kwantung Army seizes Manchuria. The famine of 1932–33 is on the record panel. It is not a tile.",
    ],
    source: "Bosworth, Mussolini; Evans, The Coming of the Third Reich; Applebaum, Red Famine",
    cause: "Crisis plus a decision by men who already held office.",
    effect: "Two dictators are in power by 1933, by different doors, and Germany’s republic has been switched off.",
    snapshot: Y1933,
    solemnId: "holodomor",
    question: {
      prompt: "Which door did Hitler use in January 1933?",
      choices: [
        "Appointment by President Hindenburg, without a majority.",
        "A successful rerun of the Beer Hall Putsch.",
        "A League of Nations mandate.",
        "The March on Rome, which he led in person.",
      ],
      answer: 0,
      explain: "The putsch failed in 1923. The office came by appointment on 30 January 1933. The March on Rome was Mussolini’s, in 1922.",
    },
    cards: hands({
      allies: [
        c("q-appoint", "event", "Appointment, not fate", "Name Hindenburg’s choice as the act that made Hitler chancellor.", "The Depression was the condition. The appointment was the act. Both belong in the sentence.", true),
        c("q-fate", "event", "It was automatic", "The Depression made a German dictatorship automatic.", "Britain and the United States were in the same Depression and did not appoint a Nazi chancellor.", false),
      ],
      soviet: [
        c("q-famine", "event", "Policy, not weather alone", "The 1932–33 famine followed seizure and blockade, not only a bad crop.", "Read the record panel. Applebaum’s figure for Ukraine is about 3.9 million dead.", true),
        c("q-weather", "event", "Only a drought", "Nothing political happened in the countryside in 1932.", "Collectivization was state policy. The deaths are not a natural footnote.", false),
      ],
      axis: [
        c("q-two-doors", "event", "Two different doors", "Rome was a king’s bargain in 1922. Munich in 1923 was a failed coup. Berlin in 1933 was an appointment.", "If you can say those three dates, you have the rise.", true),
        c("q-one-door", "event", "One method", "All three events were successful street coups.", "Only the story is similar. The results were not. The 1923 coup failed.", false),
      ],
      analyst: [
        c("q-enabling", "treaty", "Read the act", "The Enabling Act of 23 March 1933 let the cabinet legislate without the Reichstag.", "The Social Democrats voted no. Communist deputies were already out of the chamber. The law was the dictatorship.", true),
        c("q-posters", "propaganda", "Posters were enough", "No statute had to change once the rallies were large.", "The fire decree and the Enabling Act changed the law. Rallies did not replace them.", false),
      ],
      chinaSpain: [
        c("q-mukden", "event", "1931 is not 1941", "Manchuria was seized in 1931. Tojo became prime minister in 1941.", "Mukden was 18 September 1931. The premiership was 18 October 1941. Keep the decade in between.", true),
        c("q-same", "event", "Same year", "Mukden, Pearl Harbor, and the Enabling Act happened in 1933.", "Only the Enabling Act is 1933. Mukden is 1931. Pearl Harbor is 1941.", false),
      ],
    }),
    asides: [
      { title: "Weimar", text: "Until 30 January 1933 the German tile is a republic. Do not paint it early." },
      { title: "Plan", text: "The first Five-Year Plan was launched in 1928, before Hitler was chancellor." },
    ],
    portrait: "hitler",
  },
  {
    id: "quick-appease",
    startYear: 1934,
    endYear: 1939,
    ticker: "1939",
    name: "Appeasement breaks",
    headline: "THE PROMISE DOES NOT HOLD",
    dateline: "1938–1939",
    deck: "Munich gives away the Sudetenland. Six months later German troops are in Prague. In September, Poland.",
    pages: [
      "Rhineland, 7 March 1936: no one fights. Ethiopia falls in May 1936. Spain’s civil war runs from July 1936 to April 1939, with German and Italian aid to Franco and the bombing of Guernica on 26 April 1937. China’s war with Japan widens on 7 July 1937. Nanjing falls that December. The Soviet purge of 1936–38 kills about 680,000 people by archival count.",
      "Anschluss, 12 March 1938. Munich, 29–30 September 1938, without Czechoslovakia at the table. Prague, 15 March 1939. Albania, 7 April 1939. The Nazi-Soviet Pact, 23 August 1939, with a secret protocol. Poland, 1 September. Britain and France declare war on 3 September. The Soviet Union enters eastern Poland on 17 September.",
    ],
    source: "Evans, The Third Reich in Power; Preston, Franco; Mitter, China's War with Japan",
    cause: "A string of bargains taught Hitler that the next border would also move without a general war.",
    effect: "The Munich promise died in Prague, and a pact with Stalin opened the attack on Poland.",
    snapshot: Y1939,
    solemnId: "nanjing",
    badge: "warning-signs",
    question: {
      prompt: "Which order is correct?",
      choices: [
        "Munich in September 1938, Prague in March 1939, Poland in September 1939.",
        "Poland in 1936, Munich in 1941, Prague in 1922.",
        "Prague, then the Rhineland, then the March on Rome.",
        "Pearl Harbor, then the Anschluss, then the Enabling Act.",
      ],
      answer: 0,
      explain: "The Sudetenland was ceded at the end of September 1938. The rest of Bohemia and Moravia was occupied on 15 March 1939. Poland was invaded on 1 September 1939.",
    },
    cards: hands({
      allies: [
        c(
          "q-munich-cost",
          "response",
          "Name the cost",
          "Munich traded the Sudetenland for a promise Hitler broke in March.",
          "Chamberlain said “peace for our time.” Churchill was not prime minister. The what-if of fighting in 1936 or refusing in 1938 was not free of risk, and it was real.",
          true,
          true,
        ),
        c("q-munich-end", "response", "Last demand", "Munich ended Hitler’s expansion.", "Prague in March 1939 shows it did not.", false),
      ],
      soviet: [
        c("q-pact-card", "alliance", "Say the protocol", "The August 1939 pact had a secret territorial deal, and the Soviet Union invaded eastern Poland.", "23 August, then 17 September. The Winter War against Finland began on 30 November 1939.", true),
        c("q-pact-clean", "alliance", "A clean peace", "The pact had no secret clauses.", "The protocol was the point of the bargain. Leaving it out is a false summary.", false),
      ],
      axis: [
        c("q-sequence", "event", "Keep the sequence", "Rhineland, Anschluss, Sudetenland, Prague, Poland. That is the spine.", "1936, March 1938, September 1938, March 1939, September 1939. Ethiopia and Spain sit beside this spine, not instead of it.", true),
        c("q-jumble", "event", "Dates are flexible", "Students may swap 1936 and 1939 if the story feels right.", "The story feels right only with the dates. Swapping them invents a different decade.", false),
      ],
      analyst: [
        c("q-absent", "treaty", "The empty chair", "Czechoslovakia was the subject of Munich and not a signer.", "A treaty about a country, made without that country, is a warning sign. Mark it.", true),
        c("q-signed", "propaganda", "Everyone agreed", "Four signatures mean the Czechs agreed.", "They were not the four. Agreement was announced to them.", false),
      ],
      chinaSpain: [
        c("q-guernica", "event", "Guernica’s date", "26 April 1937. German and Italian aircraft bombed a Basque town during the civil war.", "Franco was not yet the ruler of all Spain. The war ended on 1 April 1939. Nanjing is a different crime, in a different war, that same era.", true),
        c("q-guernica-wrong", "event", "Guernica was in Poland", "The bombing was the start of the invasion of Poland.", "Poland was September 1939. Guernica was April 1937, in Spain.", false),
      ],
    }),
    asides: [
      { title: "Purge", text: "The Great Terror of 1936–38 overlapped these foreign crises. About 680,000 people were executed in 1937 and 1938." },
      { title: "Kristallnacht", text: "On 9–10 November 1938 a state-backed pogrom burned synagogues and attacked Jews across Germany." },
    ],
    portrait: "chamberlain",
  },
  {
    id: "quick-war",
    startYear: 1940,
    endYear: 1943,
    ticker: "1943",
    name: "War and the turn",
    headline: "STALINGRAD, THEN A DISMISSAL",
    dateline: "1940–1943",
    deck: "France falls. Britain holds. The Soviet Union is invaded and does not collapse. Mussolini is removed.",
    pages: [
      "9 April 1940: Denmark and Norway. Sweden stays neutral. 10 May: the Low Countries, France, and Churchill’s premiership. Armistice 22 June, Vichy under Pétain, de Gaulle’s appeal on 18 June. The Battle of Britain prevents an invasion. April 1941: Yugoslavia and Greece. 22 June 1941: Barbarossa. 7 December 1941: Pearl Harbor. Tojo has been prime minister since 18 October.",
      "Midway, 4–7 June 1942. The Sixth Army surrenders at Stalingrad on 2 February 1943. North Africa is cleared of Axis forces in May. The king dismisses Mussolini on 25 July 1943. The Holocaust is on the record panel: six million Jews, and millions of others. It is not a battle result.",
    ],
    source: "Evans, The Third Reich at War; United States Holocaust Memorial Museum",
    cause: "Fast victories in 1940 led to a wider war the Axis could not finish.",
    effect: "By the end of 1943 the advance had broken in the east, in Africa, and in the Pacific, and Italy had changed sides.",
    snapshot: Y1943,
    solemnId: "holocaust",
    badge: "turning",
    battle: {
      id: "stalingrad",
      title: "Stalingrad",
      date: "2 February 1943",
      attacker: "German Sixth Army",
      defender: "Soviet armies",
      historical: "defender",
      summary: "The surrender stopped the German advance. France was still occupied. Hold both facts.",
      fromId: "germany",
      toId: "wsoviet",
    },
    question: {
      prompt: "Which statement keeps 1940 and 1943 in the right order?",
      choices: [
        "France fell in June 1940. The Sixth Army surrendered at Stalingrad in February 1943.",
        "Stalingrad came before the invasion of Poland.",
        "Pearl Harbor caused the Munich Agreement.",
        "Mussolini was dismissed in 1922.",
      ],
      answer: 0,
      explain: "The armistice was 22 June 1940. Stalingrad’s surrender was 2 February 1943. Mussolini’s dismissal was 25 July 1943, not the March on Rome.",
    },
    cards: hands({
      allies: [
        c("q-britain-holds", "response", "Britain holds", "The Battle of Britain stopped an invasion in 1940. D-Day is still four years away.", "Churchill became prime minister on 10 May 1940. The island was not occupied.", true),
        c("q-britain-falls", "response", "Britain fell in June", "The armistice of June 1940 included a British surrender.", "France signed the armistice. Britain did not.", false),
      ],
      soviet: [
        c("q-not-done", "event", "Not a finished conquest", "Barbarossa seized land and did not end the Soviet state.", "22 June 1941 opens the front. February 1943 shows it can be broken. About 27 million Soviet people died in the war.", true),
        c("q-collapsed", "event", "The state collapsed in June", "The Soviet government surrendered in the first week.", "It did not. Moscow did not fall in 1941.", false),
      ],
      axis: [
        c("q-tojo-pearl", "event", "October, then December", "Tojo became prime minister on 18 October 1941. Pearl Harbor was 7 December.", "Hirohito approved the war and was not tried. He was the emperor, not the prime minister.", true),
        c("q-tojo-1931", "event", "Premier in 1931", "Tojo ordered Pearl Harbor in the Mukden year.", "Mukden was 1931. The premiership and Pearl Harbor were 1941.", false),
      ],
      analyst: [
        c("q-vichy-deg", "propaganda", "Two French voices", "Pétain headed Vichy. De Gaulle rejected the armistice on 18 June 1940.", "Same month, opposite choices. Collaboration is a policy, not a national character.", true),
        c("q-same-voice", "propaganda", "They agreed", "Pétain and de Gaulle issued one joint appeal.", "They did not. The appeal of 18 June was against the armistice Pétain sought.", false),
      ],
      chinaSpain: [
        c("q-franco-out", "alliance", "Spain stays out", "Franco won in 1939 and did not declare war on the Allies.", "Hendaye was October 1940. A Blue Division later fought in the east. There was still no Spanish declaration of war.", true),
        c("q-franco-in", "alliance", "Spain is Vichy", "Franco signed the French armistice.", "Pétain led Vichy. Franco led Spain. Different men, different choices.", false),
      ],
    }),
    asides: [
      { title: "Midway", text: "4–7 June 1942. Four Japanese carriers were sunk. The Pacific advance stopped expanding." },
      { title: "Lend-Lease", text: "American supply to Allied countries was law from 11 March 1941, before Pearl Harbor." },
    ],
    portrait: "stalin",
  },
  {
    id: "quick-legacy",
    startYear: 1944,
    endYear: 1975,
    ticker: "1975",
    name: "Collapse and what lasted",
    headline: "THE WAR ENDS. THE MAP DOES NOT RESET.",
    dateline: "1944–1975",
    deck: "D-Day, the surrenders, the trials, and a Spanish dictator who dies in 1975.",
    pages: [
      "D-Day was 6 June 1944. Tojo resigned on 18 July 1944. Roosevelt died on 12 April 1945. Hitler died on 30 April. Mussolini was killed on 28 April. Germany surrendered in May. Hiroshima was 6 August, Nagasaki 9 August, and Japan’s formal surrender was 2 September 1945. Nuremberg opened on 20 November 1945. Tojo was executed on 23 December 1948. Hirohito was not tried.",
      "Yalta and Potsdam left the Soviet army’s presence in Eastern Europe as a political fact. Stalin died on 5 March 1953. Mao proclaimed the People’s Republic on 1 October 1949 and still ruled in 1975. Franco died on 20 November 1975. Greece did not become a Soviet satellite. Yugoslavia broke with Stalin. Those exceptions keep the word “Balkans” from becoming one false color.",
    ],
    source: "Office of the Historian; Preston, Franco; Khlevniuk, Stalin",
    cause: "Allied victory destroyed the Axis states and did not install democracies everywhere the armies stood.",
    effect: "Trials, a divided Europe, a communist China, and Franco’s long rule.",
    snapshot: Y1975,
    question: {
      prompt: "Which leader was still in power in November 1975?",
      choices: [
        "Francisco Franco, until his death on 20 November 1975.",
        "Adolf Hitler.",
        "Benito Mussolini.",
        "Hideki Tojo.",
      ],
      answer: 0,
      explain: "Hitler and Mussolini died in April 1945. Tojo was executed in 1948. Franco died on 20 November 1975. Mao was also still alive in 1975 and died in 1976.",
    },
    cards: hands({
      allies: [
        c("q-dates-end", "event", "Separate the surrenders", "Germany surrendered in May 1945. Japan surrendered in August and September.", "VE Day is not VJ Day. Truman, not Roosevelt, was president for both surrenders, because Roosevelt died on 12 April.", true),
        c("q-one-day", "event", "One signature", "A single ceremony on 30 April ended both wars.", "30 April is the day Hitler died. Japan’s signing was 2 September.", false),
      ],
      soviet: [
        c("q-yalta", "treaty", "Presence, then a sphere", "At Yalta the Soviet army was already in Eastern Europe. Free elections in Poland were promised and not delivered.", "Yalta was 4–11 February 1945. Potsdam was that summer, with Truman. Stalin died on 5 March 1953.", true),
        c("q-yalta-magic", "treaty", "A clause did all of it", "No army was involved. A paragraph created the bloc.", "The paragraph and the army were both real. Leaving the army out is a fairy tale.", false),
      ],
      axis: [
        c("q-outlived", "event", "Who was gone", "By 1948 Hitler, Mussolini, and Tojo were dead. Franco was not.", "That is the reason the timeline is long. The Axis desk does not get points for the years Franco kept.", true),
        c("q-all-dead", "event", "All dead in 1945", "Franco and Stalin died in the bunker with Hitler.", "Stalin died in 1953. Franco died in 1975. Neither was in that bunker.", false),
      ],
      analyst: [
        c("q-trials", "response", "The court is part of the end", "Nuremberg and Tokyo were how the Allies named the crimes in public.", "The major Nuremberg trial ran from November 1945 to October 1946. It is not a level to beat.", true),
        c("q-skip-trial", "response", "Skip the courts", "Battlefield dates are enough, and trials are optional.", "A class that can list D-Day and cannot say what Nuremberg was for has half the unit.", false),
      ],
      chinaSpain: [
        c("q-1975", "event", "Two capitals, 1975", "Franco dies in Madrid on 20 November 1975. Mao still rules in Beijing. Chiang is on Taiwan.", "Chiang also died in 1975, on 5 April. The People’s Republic dates from 1 October 1949.", true),
        c("q-chiang-beijing", "event", "Chiang in Beijing", "The Nationalists governed the mainland in 1975.", "They had not since 1949. The mainland government was Mao’s.", false),
      ],
    }),
    asides: [
      { title: "Hirohito", text: "The emperor announced surrender on 15 August 1945 and was not charged. Debate about his role is part of the lesson, not a trivia trick." },
      { title: "Greece", text: "After occupation, Greece had a civil war and stayed outside the Soviet bloc. Do not color the whole Balkans as Moscow’s." },
    ],
    portrait: "franco",
  },
];

export function erasFor(length: Length): EraDef[] {
  return length === "quick" ? QUICK_ERAS : FULL_ERAS;
}

export function allEras(): EraDef[] {
  return [...FULL_ERAS, ...QUICK_ERAS];
}
